In [13]:
import torch

tensor_0 = torch.tensor(
    [
   [1.0, 1.2, 1.9],
    [2.3, 3.4, 3.9],
    [4.5, 5.7, 5.9],
    ]
)
print(tensor_0)


tensor([[1.0000, 1.2000, 1.9000],
        [2.3000, 3.4000, 3.9000],
        [4.5000, 5.7000, 5.9000]])


In [15]:
index = torch.tensor(
    [
    [0, 1],
    [1, 2],
    ]
)
tensor_1 = tensor_0.gather(0, index)
print(tensor_1)

tensor([[1.0000, 3.4000],
        [2.3000, 5.7000]])


In [16]:
index = torch.tensor(
    [
    [0, 1],
    [1, 2],
    ]
)
tensor_1 = tensor_0.gather(1, index)
print(tensor_1)

tensor([[1.0000, 1.2000],
        [3.4000, 3.9000]])
