In [ ]:
import torch

# 设置随机种子以便结果可复现
torch.manual_seed(0)

# 定义矩阵尺寸
bsz = 16
nt = 1
kv_lora = 512

# 随机生成两个矩阵
matrix_a = torch.randn(bsz, nt,kv_lora)
matrix_a =matrix_a.unsqueeze(-3)



# 输出结果形状
print(matrix_a.shape)

# # 如果需要，可以将输出reshape回原始形状
# output_reshaped = output.view(bsz, q_len, num_heads * nope_plus_rope)
# print(output_reshaped.shape)

torch.Size([16, 1, 2, 512])


In [4]:
import torch


torch.manual_seed(0)

# 定义矩阵尺寸
nh = 16
nt = 1
nope=64
kv_lora = 512

# 随机生成两个矩阵
matrix_a = torch.randn(nh, nt,nope)
matrix_b =torch.randn(nh, nope,kv_lora)




# 输出结果形状
print(torch.matmul(matrix_a,matrix_b).shape)

# # 如果需要，可以将输出reshape回原始形状
# output_reshaped = output.view(bsz, q_len, num_heads * nope_plus_rope)
# print(output_reshaped.shape)

torch.Size([16, 1, 512])


In [8]:
import torch


torch.manual_seed(0)

# 定义矩阵尺寸
bsz=2
nh = 16
nt = 1
nope=64
kv_lora = 512

# 随机生成两个矩阵
matrix_a = torch.randn(bsz,nh, nt,nope)





# 输出结果形状
print(matrix_a.transpose(1,2).shape)

# # 如果需要，可以将输出reshape回原始形状
# output_reshaped = output.view(bsz, q_len, num_heads * nope_plus_rope)
# print(output_reshaped.shape)

torch.Size([2, 1, 16, 64])


In [11]:
import torch


torch.manual_seed(0)

# 定义矩阵尺寸
ext_l=16
t_l=5
nh = 16
nt = 1
nope=64
kv_lora = 512
base=1000
dim=32
inv_freq = 1.0 / (base ** (torch.arange(0, dim, 2).float() /dim))
# 随机生成两个矩阵
ext_factors = torch.randn(ext_l)
t= torch.randn(t_l)
tmp= torch.outer(t, 1.0 / ext_factors)
print(tmp.shape)
print(inv_freq.shape)
r=torch.mul(
    tmp,
    inv_freq
)
print(inv_freq)
print(tmp)
print(r)
    # freqs = torch.mul(
    #         # s*16
           
    #         self.inv_freq.to(device=device).to(dtype)
    #     )




torch.Size([5, 16])
torch.Size([16])
tensor([1.0000, 0.6494, 0.4217, 0.2738, 0.1778, 0.1155, 0.0750, 0.0487, 0.0316,
        0.0205, 0.0133, 0.0087, 0.0056, 0.0037, 0.0024, 0.0015])
tensor([[ 0.6389,  0.6242,  2.8704,  1.6577, -0.8475, -1.0394,  2.2760,  0.3400,
         -2.2318,  0.5693, -2.0551, -2.3342, -6.0017, -0.5811, -0.6440,  2.9087],
        [ 0.3583,  0.3500,  1.6096,  0.9296, -0.4752, -0.5829,  1.2764,  0.1907,
         -1.2516,  0.3193, -1.1525, -1.3090, -3.3656, -0.3259, -0.3612,  1.6311],
        [ 0.5299,  0.5178,  2.3810,  1.3751, -0.7030, -0.8622,  1.8880,  0.2821,
         -1.8513,  0.4723, -1.7048, -1.9363, -4.9785, -0.4821, -0.5342,  2.4128],
        [-0.1617, -0.1580, -0.7265, -0.4196,  0.2145,  0.2631, -0.5760, -0.0861,
          0.5648, -0.1441,  0.5201,  0.5908,  1.5190,  0.1471,  0.1630, -0.7362],
        [ 0.7609,  0.7434,  3.4188,  1.9745, -1.0094, -1.2380,  2.7109,  0.4050,
         -2.6582,  0.6781, -2.4478, -2.7802, -7.1484, -0.6922, -0.7671,  3.4644]])
te

In [6]:
import torch

# 创建一个示例张量 x，形状为 (2, 8)
x = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8],
                  [8, 7, 6, 5, 4, 3, 2, 1]])

def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)

# 应用 rotate_half 函数到 x 上
result = rotate_half(x)

print("Original tensor:")
print(x)
print("\nAfter applying rotate_half:")
print(result)

Original tensor:
tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1]])

After applying rotate_half:
tensor([[-5, -6, -7, -8,  1,  2,  3,  4],
        [-4, -3, -2, -1,  8,  7,  6,  5]])


In [8]:
p=2.7943e-01*0.5864+3.0990e+00*8.1001e-01
print(p)

2.6740787420000003


# 爱因斯坦

In [12]:
import torch
a = torch.rand(2,3)
b = torch.rand(3,4)
c = torch.einsum("ik,kj->ij", [a, b])
print(c.shape)

torch.Size([2, 4])


In [1]:
import torch

# 假设 b=2, h=3, q=4, l=5, c=6 作为例子
b, h, q, l, c = 2, 3, 4, 5, 6

# 创建示例张量
attn_weights = torch.randn(b, h, q, l)
compressed_kv = torch.randn(b, l, c)

result=torch.einsum('bhql,blc->bhqc', attn_weights, compressed_kv)

compressed_kv_expanded = compressed_kv.unsqueeze(1)  # 形状变为 [bsz, 1, nt, dkv_lora]

# 执行批量矩阵乘法
attn_output = torch.matmul(attn_weights, compressed_kv_expanded)  # 输出形状 [bsz, nh, nt,

print(torch.equal(result,attn_output))  # 应该打印出 torch.Size([2, 3, 4, 6])

True
